### ISSUE TITLE
数据加解密的方式有吗？

### ISSUE THREAD

**Issue by flylihaoooo** [ch0ice/jt809-tcp-server#1]

**Comment by ch0ice** [comment]
没有理解您的意思，你可以描述的具体点，你指的数据加解密是编解码吗？

**Comment by ch0ice** [comment]
抱歉，迟来的回复，这段时间没有关注github，身体出了问题一直在往返医院~
没有理解您的意思，你可以描述的具体点，你指的数据加解密是编解码吗？809或大多数tcp协议都是直接按位解析的二进制流，没有单独对数据进行加解密。
